name: 'Closed issue labeler'

on:
  issues:
    types: [closed]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ contains(github.event.issue.labels.*.name, 'bug') || contains(github.event.issue.labels.*.name, 'enhancement') }}
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          labels: Solved
